### ISSUE TITLE
this project support pipeline without build and git?

### ISSUE THREAD

**Issue by fanux** [cncd/pipeline#18]
We want a container pipeline system not trigger by git event, and don't have a git repository in our cluster.   Need a pipeline like this:
```
pipeline:
   conf:
     image:confd:latest
     ...
   upcontainers:
     image: compose:latest
     ..
   ...
```

**Comment by dolanor** [comment]
If I'm not mistaken, pipeline is not triggered by anything. It is only when used by drone that it needs to be triggered by an webhook with git-like data in JSON.
But pipeline, you just execute it whenever you want, and it works.

**Comment by tboerger** [comment]
But drone is focused on a pipeline defined within a git repository and triggered by changes to this git repository.

**Comment by fanux** [comment]
@dolanor but the compile command has a lot of repo argument, how can I convert `yaml` to `json` using the command, I needn't the git arguments

**Comment by dolanor** [comment]
@fanux you're quite right. I guess I forgot about it…
