### ISSUE TITLE
bug in tailing logs in docker

### ISSUE THREAD

**Issue by shachartal** [cncd/pipeline#29]
[Here](https://github.com/cncd/pipeline/blob/master/pipeline/backend/docker/docker.go#L165) we should not be closing `rc` - it needs to be closed by the actual reader (consuming the return value of the enclosing method), after it's done with the data.

**Comment by bradrydzewski** [comment]
project is moving to [drone-runtime](https://github.com/drone/drone-runtime) and this issue has been closed
