### ISSUE TITLE
yaml parser treating string as float

### ISSUE THREAD

**Issue by bradrydzewski** [cncd/pipeline#9]
yaml parser interprets `9214e21` as float when it is meant to be a string. This actually sort of makes sense, since it matches a float pattern.
https://github.com/cncd/pipeline/blob/master/pipeline/frontend/yaml/compiler/params.go

The solution probably involves formatting the float with explicit precision as described in the [fmt](https://golang.org/pkg/fmt/) package documentation

```
%f     default width, default precision
%9f    width 9, default precision
%.2f   default width, precision 2
%9.2f  width 9, precision 2
%9.f   width 9, precision 0
```

below is the original issue as logged

---

we have meet a bug in drone 0.5 while using plugins/docker

this is one stage in our pipeline:

dockerize-online:
    image: plugins/docker
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    debug: true
    repo: docker-registry-cn.easemob.com/kubernetes/im/eva-web
    tags: ${DRONE_COMMIT:0:7}
    registry: https://docker-registry-cn.easemob.com
    username: xxx
    password: xxx
    dockerfile: image/docker/eva-web/Dockerfile
    context: image/docker/eva-web/
    volumes:
      - /data/apps/opt/eva:/data/apps/opt/eva
    when:
      branch: release
and we got these error output:

...
192 Successfully tagged 9214e217d1f484e6607d67c6dc214740c918e0e2:latest
193 + /usr/local/bin/docker tag 9214e217d1f484e6607d67c6dc214740c918e0e2 docker-registry-cn.easemob.com/kubernetes/im/eva-web:9.214e+24
194 Error parsing reference: "docker-registry-cn.easemob.com/kubernetes/im/eva-web:9.214e+24" is not a valid repository/tag: invalid reference format
195 time="2017-05-23T07:18:54Z" level=fatal msg="exit status 1" 
I think this is a bug of go substring !

docker-registry-cn.easemob.com/kubernetes/im/eva-web:9.214e+24
should be
docker-registry-cn.easemob.com/kubernetes/im/eva-web:9214e21

**Comment by wk3368** [comment]
I have test the func paramsToEnv() with go 1.8.1, there is no problem indeed!

```
package main

import (
	"fmt"
	"reflect"
	"strconv"
	"strings"

	json "github.com/ghodss/yaml"
	"gopkg.in/yaml.v2"
)

func main() {

	byt := []byte(`{"tags":9214e21}`)

	var from map[string]interface{}

	if err := json.Unmarshal(byt, &from); err != nil {
		panic(err)
	}

	fmt.Println(from)

	to := map[string]string{}

	if err := paramsToEnv(from, to); err != nil {
		fmt.Printf("%s", err)
	}
	fmt.Println(to)
}

func paramsToEnv(from map[string]interface{}, to map[string]string) error {
	for k, v := range from {
		if v == nil {
			continue
		}

		t := reflect.TypeOf(v)
		vv := reflect.ValueOf(v)

		k = "PLUGIN_" + strings.ToUpper(k)

		fmt.Printf("t=%v,vv=%v,k=%v,kind=%v\n", t, vv, k, t.Kind())

		switch t.Kind() {
		case reflect.Bool:
			to[k] = strconv.FormatBool(vv.Bool())

		case reflect.String:
			to[k] = vv.String()

		case reflect.Int, reflect.Int16, reflect.Int32, reflect.Int64, reflect.Int8:
			to[k] = fmt.Sprintf("%v", vv.Int())

		case reflect.Float32, reflect.Float64:
			to[k] = fmt.Sprintf("%v", vv.Float())

		case reflect.Map:
			yml, _ := yaml.Marshal(vv.Interface())
			out, _ := json.YAMLToJSON(yml)
			to[k] = string(out)

		case reflect.Slice:
			out, err := yaml.Marshal(vv.Interface())
			if err != nil {
				return err
			}

			in := []string{}
			err = yaml.Unmarshal(out, &in)
			if err == nil {
				to[k] = strings.Join(in, ",")
			} else {
				out, err = json.YAMLToJSON(out)
				if err != nil {
					return err
				}
				to[k] = string(out)
			}
		}
	}

	return nil
}
```

the output is as expect:
```
map[tags:9214e21]
t=string,vv=9214e21,k=PLUGIN_TAGS,kind=string
map[PLUGIN_TAGS:9214e21]
```

is the problem the go version which build the  plugins/docker image?

**Comment by bradrydzewski** [comment]
I haven't been able to track this down, but it turns out we had an existing issue for this. So let's continue to track this here https://github.com/drone-plugins/drone-docker/issues/113
